"""Python equivalents of the MATLAB signal-processing calls used by the
original feature-extraction scripts.

The MATLAB code leans on ``smoothdata(...,'loess',span)``,
``smoothdata(...,'gaussian',span)`` and ``findpeaks(...,'MinPeakProminence',p)``.
The first two have no direct SciPy counterpart, so they are reimplemented here
following MATLAB's own algorithm (``matlab/datafun/+matlab/+internal/+math/
localRegression.m``) rather than the textbook definitions, which differ at the
window edges:

* ``span`` counts *samples*, not a fraction of the signal.
* ``loess`` fits a local **quadratic** with tricube weights over the
  ``2*floor(span/2)-1`` samples nearest each point, normalising distances by
  ``floor(span/2)``.
* The first and last ``ceil(span/2)`` samples are special-cased: each is
  regressed against the whole leading (or trailing) block of ``span`` samples,
  with distances normalised by the *forward* extent.
* ``gaussian`` uses a Gaussian kernel of standard deviation ``span/5``,
  truncated to a centred window of ``span`` samples and renormalised.

``scripts/00_verify_dataset.py`` checks all of this against MATLAB output
generated by ``matlab/export_smoothing_reference.m``.
"""

from __future__ import annotations

import numpy as np
from scipy.signal import find_peaks


# ---------------------------------------------------------------------------
# Smoothing
# ---------------------------------------------------------------------------


def _tricube_sqrt(distance: np.ndarray, dmax: float) -> np.ndarray:
    """``(1 - |d/dmax|^3)^(3/2)`` -- the square root of the tricube weight.

    MATLAB scales the Vandermonde matrix by this, which is the usual
    square-root-of-weights formulation of weighted least squares.
    """
    if dmax <= 0:
        return np.ones_like(distance, dtype=float)
    t = np.abs(distance) / dmax
    return np.clip(1.0 - t**3, 0.0, None) ** 1.5


def _projection_row(distance: np.ndarray, sqrt_w: np.ndarray, row: int, degree: int) -> np.ndarray:
    """Weights that turn a block of samples into one fitted value.

    Builds the weighted Vandermonde matrix, orthonormalises it, and reads off
    the row of the hat matrix belonging to ``row``.
    """
    vander = sqrt_w[:, None] * distance[:, None] ** np.arange(degree + 1)
    q, _ = np.linalg.qr(vander)
    return (q[row, :] @ q.T) * sqrt_w


def smooth_loess(y: np.ndarray, span: int, degree: int = 2) -> np.ndarray:
    """MATLAB ``smoothdata(y, 'loess', span)``.

    ``degree=1`` gives ``'lowess'`` instead. Non-finite samples are not
    supported by this fast path and are passed through a slower generic
    fallback.
    """
    y = np.asarray(y, dtype=float)
    n = y.size
    span = min(int(span), n) if n else int(span)

    if n < 2 or span < 2:
        return y.copy()
    if not np.isfinite(y).all():
        return _smooth_loess_with_gaps(y, span, degree)

    # --- interior: a fixed FIR filter -------------------------------------
    dmax = span // 2
    xlim = dmax - 1
    offsets = np.arange(-xlim, xlim + 1, dtype=float)
    sqrt_w = _tricube_sqrt(offsets, dmax)

    vander = sqrt_w[:, None] * offsets[:, None] ** np.arange(degree + 1)
    q, _ = np.linalg.qr(vander)
    kernel = (q @ q[xlim, :]) * sqrt_w

    out = np.convolve(y, kernel, mode="same")

    # --- endpoints: regress each against the whole leading/trailing block --
    n_end = min(-(-span // 2), n // 2 + n % 2)  # ceil(span/2), clipped
    front = y[:span]
    back = y[n - 1 : n - 1 - span : -1]

    block = np.arange(span, dtype=float)
    for j in range(1, n_end + 1):
        distance = block - (j - 1)
        forward_extent = span - j
        sqrt_we = _tricube_sqrt(distance, forward_extent)
        alpha = _projection_row(distance, sqrt_we, j - 1, degree)

        keep = sqrt_we != 0
        out[j - 1] = alpha[keep] @ front[keep]
        out[n - j] = alpha[keep] @ back[keep]

    return out


def _smooth_loess_with_gaps(y: np.ndarray, span: int, degree: int) -> np.ndarray:
    """Fallback for signals containing NaN: per-point weighted fit, NaNs skipped."""
    n = y.size
    back = span // 2
    fwd = span - back - 1
    dmax = float(span // 2)
    out = np.empty(n, dtype=float)

    for i in range(n):
        a, b = max(i - back, 0), min(i + fwd, n - 1)
        distance = np.arange(a, b + 1, dtype=float) - i
        values = y[a : b + 1]

        sqrt_w = _tricube_sqrt(distance, dmax)
        keep = np.isfinite(values) & (sqrt_w != 0)
        if keep.sum() <= degree:
            out[i] = np.nanmean(values) if np.isfinite(values).any() else np.nan
            continue

        d, sw, vals = distance[keep], sqrt_w[keep], values[keep]
        vander = sw[:, None] * d[:, None] ** np.arange(degree + 1)
        coef, *_ = np.linalg.lstsq(vander, sw * vals, rcond=None)
        out[i] = coef[0]

    return out


def smooth_gaussian(y: np.ndarray, span: int) -> np.ndarray:
    """MATLAB ``smoothdata(y, 'gaussian', span)``.

    Gaussian-weighted moving average, kernel standard deviation ``span/5``,
    truncated to a centred window of ``span`` samples. Edges and NaNs are
    handled by renormalising the kernel over whatever samples are available,
    which is what MATLAB's default ``'omitnan'`` does.
    """
    y = np.asarray(y, dtype=float)
    n = y.size
    span = int(span)
    if n == 0 or span <= 1:
        return y.copy()

    back = span // 2
    fwd = span - back - 1
    offsets = np.arange(-back, fwd + 1, dtype=float)
    kernel = np.exp(-0.5 * (offsets / (span / 5.0)) ** 2)

    # np.convolve reverses the kernel; ours is not symmetric for even spans.
    kernel = kernel[::-1]

    valid = np.isfinite(y)
    filled = np.where(valid, y, 0.0)

    numerator = np.convolve(filled, kernel, mode="same")
    denominator = np.convolve(valid.astype(float), kernel, mode="same")

    with np.errstate(invalid="ignore", divide="ignore"):
        out = numerator / denominator
    out[denominator == 0] = np.nan
    return out


# ---------------------------------------------------------------------------
# Peak detection
# ---------------------------------------------------------------------------


def find_extremum(
    x: np.ndarray,
    y: np.ndarray,
    window: tuple[float, float],
    *,
    kind: str,
    prominence: float,
) -> tuple[float, float]:
    """Locate one peak (``kind='max'``) or valley (``kind='min'``) inside a window.

    Mirrors the MATLAB pattern ``findpeaks(Y,'MinPeakProminence',p)`` followed by
    picking the most extreme candidate. Returns ``(nan, nan)`` when nothing in
    the window clears the prominence threshold -- which is how the original code
    marks a peak that ageing has flattened past recognition.
    """
    if kind not in {"max", "min"}:
        raise ValueError(f"kind must be 'max' or 'min', got {kind!r}")

    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)

    mask = (x >= window[0]) & (x <= window[1]) & np.isfinite(y)
    if not mask.any():
        return np.nan, np.nan

    xs, ys = x[mask], y[mask]
    signal = ys if kind == "max" else -ys

    locs, _ = find_peaks(signal, prominence=prominence)
    if locs.size == 0:
        return np.nan, np.nan

    best = locs[np.argmax(signal[locs])]
    return float(xs[best]), float(ys[best])


def find_extremum_or_global(
    x: np.ndarray,
    y: np.ndarray,
    window: tuple[float, float],
    *,
    kind: str,
    prominence: float,
) -> tuple[float, float]:
    """As :func:`find_extremum`, but falls back to the window's global extremum.

    The DVA extraction uses this fallback so a feature is always produced, even
    once the local peak has degenerated into a shoulder.
    """
    xx, yy = find_extremum(x, y, window, kind=kind, prominence=prominence)
    if np.isfinite(xx):
        return xx, yy

    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    mask = (x >= window[0]) & (x <= window[1]) & np.isfinite(y)
    if not mask.any():
        return np.nan, np.nan

    xs, ys = x[mask], y[mask]
    idx = int(np.argmax(ys) if kind == "max" else np.argmin(ys))
    return float(xs[idx]), float(ys[idx])


def find_knee(
    x: np.ndarray,
    y: np.ndarray,
    window: tuple[float, float],
) -> tuple[float, float]:
    """Flattest point in a window -- MATLAB's ``[~,i] = min(abs(diff(Y)))``.

    Used for the aged-cell DVA charge Peak B, where the peak has degenerated
    into a shoulder and a prominence-based search no longer finds anything.
    """
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)

    mask = (x >= window[0]) & (x <= window[1]) & np.isfinite(y)
    if mask.sum() < 2:
        return np.nan, np.nan

    xs, ys = x[mask], y[mask]
    idx = int(np.argmin(np.abs(np.diff(ys))))
    return float(xs[idx]), float(ys[idx])
